import { ILMRole } from '../types';

export const ilmRoles: ILMRole[] = [
  {
    id: 'role-president',
    name: 'ILM President',
    shortName: 'President',
    description: 'Oversees the entire program. Ensures students are assigned to roles and the program runs according to plan.',
    category: 'misc',
    isFixed: true,
    maxCount: 1,
  },
  {
    id: 'role-qirath',
    name: "QIRA'TH",
    shortName: 'QIRATH',
    description: 'Recitation of the Holy Quran to open the meeting.',
    category: 'opening',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 3,
  },
  {
    id: 'role-dua',
    name: 'Dua',
    shortName: 'Dua',
    description: 'Supplication / prayer to begin the meeting.',
    category: 'opening',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 2,
  },
  {
    id: 'role-welcome',
    name: 'Welcome Speech',
    shortName: 'Welcome',
    description: 'Welcome address to the audience and participants.',
    category: 'opening',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 3,
  },
  {
    id: 'role-inauguration',
    name: 'Inauguration',
    shortName: 'Inauguration',
    description: 'Formal inauguration of the ILM meeting.',
    category: 'opening',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 5,
  },
  {
    id: 'role-lmod',
    name: 'LMOD',
    shortName: 'LMOD',
    expandedName: 'Learning Master of the Day',
    description: 'Controls the Prepared Speech Session and introduces the meeting theme.',
    category: 'prepared_speech',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 5,
  },
  {
    id: 'role-prepared-speaker',
    name: 'Prepared Speaker',
    shortName: 'Speaker',
    description: 'Delivers a prepared speech on an assigned bilingual topic.',
    category: 'prepared_speech',
    isFixed: false,
    defaultDurationMinutes: 5,
  },
  {
    id: 'role-tt-master',
    name: 'TT Master',
    shortName: 'TT Master',
    expandedName: 'Table Topic Master',
    description: 'Manages the Table Topics session and assigns impromptu topics.',
    category: 'table_topics',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 5,
  },
  {
    id: 'role-tt-speaker',
    name: 'TT Speaker',
    shortName: 'TT Speaker',
    expandedName: 'Table Topic Speaker',
    description: 'Delivers an impromptu speech on a topic assigned by the TT Master.',
    category: 'table_topics',
    isFixed: false,
    defaultDurationMinutes: 2,
  },
  {
    id: 'role-ice-breaking',
    name: 'Ice Breaking Speaker',
    shortName: 'Ice Breaking',
    description: 'Delivers an ice-breaking speech.',
    category: 'ice_breaking',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 5,
  },
  {
    id: 'role-evaluator1',
    name: 'Evaluator 1',
    shortName: 'Eval 1',
    description: 'Evaluates assigned prepared and TT speakers.',
    category: 'evaluation',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 3,
  },
  {
    id: 'role-evaluator2',
    name: 'Evaluator 2',
    shortName: 'Eval 2',
    description: 'Evaluates assigned prepared and TT speakers.',
    category: 'evaluation',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 3,
  },
  {
    id: 'role-evaluator3',
    name: 'Evaluator 3',
    shortName: 'Eval 3',
    description: 'Evaluates assigned prepared and TT speakers.',
    category: 'evaluation',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 3,
  },
  {
    id: 'role-general-evaluator',
    name: 'General Evaluator',
    shortName: 'GE',
    description: 'Evaluates all speakers across the program with a comprehensive report.',
    category: 'evaluation',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 4,
  },
  {
    id: 'role-grammarian',
    name: 'Grammarian',
    shortName: 'Grammarian',
    description: 'Listens to speeches, records language/grammar mistakes, and later explains corrections.',
    category: 'evaluation',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 3,
  },
  {
    id: 'role-ah-counter',
    name: 'Ah Counter',
    shortName: 'Ah Counter',
    description: 'Records pauses and stuck moments in each student\'s speech.',
    category: 'evaluation',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 2,
  },
  {
    id: 'role-timer',
    name: 'Timer',
    shortName: 'Timer',
    description: 'Records actual start/end times for all program activities.',
    category: 'evaluation',
    isFixed: true,
    maxCount: 1,
  },
  {
    id: 'role-thankyou',
    name: 'Thank You Speech',
    shortName: 'Thank You',
    description: 'Delivers the closing thank-you speech.',
    category: 'closing',
    isFixed: true,
    maxCount: 1,
    defaultDurationMinutes: 2,
  },
];

export const getRoleById = (id: string) => ilmRoles.find(r => r.id === id);
